# Generated by Django 4.0.5 on 2022-06-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dob',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='reevaluacion',
            name='age',
            field=models.SmallIntegerField(verbose_name='Edad'),
        ),
    ]
