# Generated by Django 4.0.5 on 2022-06-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0002_paciente_dob_reevaluacion_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ('-timestamp',), 'verbose_name_plural': 'a) Pacientes'},
        ),
    ]
