# Generated by Django 4.0.5 on 2022-06-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_alter_paciente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reevaluacion',
            options={'ordering': ('-timestamp',), 'verbose_name_plural': 'b) Reevaluación'},
        ),
    ]
