# Generated by Django 4.0.5 on 2022-06-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0005_alter_reevaluacion_climc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Edad'),
        ),
    ]
