# Generated by Django 4.0.5 on 2022-06-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0006_alter_paciente_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reevaluacion',
            name='age',
            field=models.SmallIntegerField(verbose_name='Edad'),
        ),
    ]
