# Generated by Django 4.0.5 on 2022-06-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0008_alter_reevaluacion_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
