# Generated by Django 4.0.5 on 2022-06-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0009_alter_paciente_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='immediate_background',
            field=models.TextField(verbose_name='Padecimiento, Razón de Abordaje o Situación Actual'),
        ),
    ]
