# Generated by Django 4.0.5 on 2022-07-02 02:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0010_alter_paciente_immediate_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='immediate_background',
            field=ckeditor.fields.RichTextField(verbose_name='Padecimiento, Razón de Abordaje o Situación Actual'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad y Lugar de Nacimiento'),
        ),
    ]
